export const uyaLevelNames: Readonly<Record<number, string>> = {
  1: 'Veldin',
  2: 'Florana',
  3: 'Starship Phoenix',
  4: 'Marcadia',
  5: 'Daxx',
  6: 'Starship Phoenix (Under Attack)',
  7: 'Annihilation Nation',
  8: 'Aquatos',
  9: 'Tyhrranosis',
  10: 'Zeldrin Starport',
  11: 'Obani Moons',
  12: 'Blackwater City',
  13: 'Holostar Studios (Ratchet)',
  14: 'Koros',
  16: 'Metropolis',
  17: 'Crash Site',
  18: 'Aridia',
  19: "Qwark's Hideout",
  20: 'Launch Site',
  21: 'Obani Draco',
  22: 'Command Center',
  23: 'Holostar Studios (Clank)',
  24: 'Insomniac Museum',
  26: 'Metropolis Ranger Missions',
  27: 'Aquatos Base',
  28: 'Aquatos Sewers',
  29: 'Tyhrranosis Ranger Missions',
  30: 'Vid-Comic Unnamed',
  31: 'Vid-Comic 1',
  32: 'Vid-Comic 4',
  33: 'Vid-Comic 2',
  34: 'Vid-Comic 3',
  35: 'Vid-Comic 5',
  36: 'Vid-Comic 1 Special Edition',
  39: 'MP: Multiplayer Menu',
  40: 'MP: Bakisi Isles',
  41: 'MP: Hoven Gorge',
  42: 'MP: Outpost X12',
  43: 'MP: Korgon Outpost',
  44: 'MP: Metropolis',
  45: 'MP: Blackwater City',
  46: 'MP: Command Center',
  47: 'MP: Blackwater Docks',
  48: 'MP: Aquatos Sewers',
  49: 'MP: Marcadia Palace',
  50: 'MP: Bakisi Isles (Split-screen)',
  51: 'MP: Hoven Gorge (Split-screen)',
  52: 'MP: Outpost X12 (Split-screen)',
  53: 'MP: Korgon Outpost (Split-screen)',
  54: 'MP: Metropolis (Split-screen)',
  55: 'MP: Blackwater City (Split-screen)',
};
